image: ruby:2.3

services:

variables:

cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths:
    - vendor/ruby
  untracked: true

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - cp .env-example .env
  - source .env
  - bundle install

after_script:
  - ./scripts/notify_hipchat.sh
stages:
  - build
  - test
  - deploy
  - notify

build:
  stage: build
  script:
    - bundle exec rake release_checks
  only:
    - production
  tags:
    - docker
  environment: production

test:
  stage: test
  script:
    - bundle exec rake spec
  only:
    - production
  tags:
    - docker
  environment: production

production:
  stage: deploy
  script:
    - "curl -X POST -F token=$TOKEN -F ref=$CI_BUILD_REF_NAME https://$GITLAB_SERVER/api/v3/projects/$CONTRL_REPO/trigger/builds"
  only:
    - production
  tags:
    - docker
  environment: production

notify:hipchat_succeded:
  stage: notify
  script:
    - ./scripts/notify_hipchat.sh -l OK -n false
  when: on_success
  tags:
    - docker
notify:hipchat_failed:
  stage: notify
  script:
    - ./scripts/notify_hipchat.sh -l CRITICAL -n true
  when: on_failure
  tags:
    - docker
  environment: production
